version: '3'

services:
  redis:
    image: redis:alpine
    container_name: transaction-authorizer
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
